<?php
$stock = new array();
#light armor
$stock[$studded_leather]=new array("33","70");
#medium armor
$stock[$chain_shirt]=new array("38","75");
$stock[$scale_mail]=new array("38","75");
$stock[$breast_plate]=new array("300","600");
$stock[$half_plate]=new array("562","1125");
#heavy armor
$stock[$ring_mail]=new array("22","45");
$stock[$chain_mail]=new array("56","113");
$stock[$splint]=new array("150","300");
$stock[$plate]=new array("1125","2250");
#shield
$stock[$shield]=new array("7","15");

#simple weapons
$stock[$dagger]=new array("1","3");
$stock[$handaxe]=new array("3","8");
$stock[$javelin]=new array("3","8");
$stock[$light_hammer]=new array("1","3");
$stock[$mace]=new array("3","8");
$stock[$sickle]=new array("0.07","2");
$stock[$spear]=new array("0.07","2");
#martial weapons
$stock[$battleaxe]=new array("7","15");
$stock[$flail]=new array("7","15");
$stock[$glaive]=new array("15","30");
$stock[$greataxe]=new array("22","45");
$stock[$greatsword]=new array("38","75");
$stock[$halberd]=new array("15","30");
$stock[$lance]=new array("7","15");
$stock[$longsword]=new array("11","22");
$stock[$maul]=new array("7","15");
$stock[$morningstar]=new array("11","22");
$stock[$pike]=new array("3","8");
$stock[$rapier]=new array("18","38");
$stock[$scimitar]=new array("18","38");
$stock[$shortsword]=new array("7","15");
$stock[$trident]=new array("3","8");
$stock[$war_pick]=new array("3","8");
$stock[$warhammer]=new array("11","22");
#adventuring gear
$stock[$ball_bearings_1000]=new array("0.07","2");
$stock[$bell]=new array("0.07","2");
$stock[$block_and_tackle]=new array("0.07","2");
$stock[$chain_10ft]=new array("3","8");
$stock[$crowbar]=new array("1","3");
$stock[$graplink_hook]=new array("1","3");
$stock[$hammer]=new array("0.07","2");
$stock[$hammer_sledge]=new array("1","3");
$stock[$hunting_trap]=new array("3","8");
$stock[$lamp]=new array("3","8");
$stock[$lantern_bullseye]=new array("7","15");
$stock[$lanter_hooded]=new array("5","10");
$stock[$lock]=new array("7","15");
$stock[$manacles]=new array("1","3");
$stock[$mirror_steel]=new array("3","8");
$stock[$miners_pick]=new array("1","3");
$stock[$piton]=new array("0.0003","0.0008");
$stock[$pot_iron]=new array("1","3");
$stock[$spikes_iron]=new array("0.07","2");
$stock[$whetstone]=new array("0.000001","0.000002");
#tools
$stock[$carpeners_tools]=new array("6","12");
$stock[$masons_tools]=new array("7","15");
$stock[$smiths_tools]=new array("15","30");
$stock[$tinkers_tools]=new array("38","75");
$stock[$horn_instrument]=new array("2","5");
