<?php
$stock=new array ();
$stock[] = new array ('name'=>'Abacus','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'2 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Acid (vial)','type'=>'Adventuring Gear','cost'=>'25 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage, Utility');
$stock[] = new array ('name'=>'Alchemist&#39;s Fire (flask)','type'=>'Adventuring Gear','cost'=>'50 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Consumable, Damage, Utility');
$stock[] = new array ('name'=>'Alchemist&#39;s Supplies','type'=>'Tool','cost'=>'50 gp','weight'=>'8 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Amulet','type'=>'Holy Symbol','cost'=>'5 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Antitoxin','type'=>'Adventuring Gear','cost'=>'50 gp','weight'=>'--','description'=>'','notes'=>'Healing, Utility');
$stock[] = new array ('name'=>'Arrows','type'=>'Ammunition','cost'=>'1 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Assassin&#39;s Blood (Ingested)','type'=>'Poison','cost'=>'150 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage');
$stock[] = new array ('name'=>'Backpack','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'5 lbs','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Bagpipes','type'=>'Tool','cost'=>'30 gp','weight'=>'6 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Ball Bearings (bag of 1,000)','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'2 lbs','description'=>'','notes'=>'Combat, Control, Utility');
$stock[] = new array ('name'=>'Barrel','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'70 lbs','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Battleaxe','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'4 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Bedroll','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'7 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Bell','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'--','description'=>'','notes'=>'Communication, Utility');
$stock[] = new array ('name'=>'Bit and Bridle','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Block and Tackle','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'5 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Blowgun','type'=>'Martial Ranged Weapon','cost'=>'10 gp','weight'=>'1 lb','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Blowgun Needles','type'=>'Ammunition','cost'=>'1 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Bomb','type'=>'Adventuring Gear','cost'=>'150 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Book','type'=>'Adventuring Gear','cost'=>'25 gp','weight'=>'5 lbs','description'=>'','notes'=>'Social, Utility');
$stock[] = new array ('name'=>'Bottle, Glass','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'2 lbs','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Breastplate','type'=>'Medium Armor','cost'=>'400 gp','weight'=>'20 lbs','description'=>'AC 14','notes'=>'Warding');
$stock[] = new array ('name'=>'Brewer&#39;s Supplies','type'=>'Tool','cost'=>'20 gp','weight'=>'9 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Bullets, Renaissance','type'=>'Ammunition','cost'=>'3 gp','weight'=>'2 lbs','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Burglar&#39;s Pack','type'=>'Equipment Pack','cost'=>'16 gp','weight'=>'47 1/2 lbs','description'=>'','notes'=>'Container, Exploration, Utility');
$stock[] = new array ('name'=>'Burnt Othur Fumes (Inhaled)','type'=>'Poison','cost'=>'500 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage');
$stock[] = new array ('name'=>'Calligrapher&#39;s Supplies','type'=>'Tool','cost'=>'10 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Caltrops (bag of 20)','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'2 lbs','description'=>'','notes'=>'Combat, Damage, Movement');
$stock[] = new array ('name'=>'Camel','type'=>'Mount','cost'=>'50 gp','weight'=>'--','description'=>'','notes'=>'Speed 50 ft., Carrying Capacity 480 lbs.');
$stock[] = new array ('name'=>'Canoe','type'=>'Adventuring Gear','cost'=>'50 gp','weight'=>'--','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Carpenter&#39;s Tools','type'=>'Tool','cost'=>'8 gp','weight'=>'6 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Carriage','type'=>'Vehicle (Land)','cost'=>'100 gp','weight'=>'600 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Cart','type'=>'Vehicle (Land)','cost'=>'15 gp','weight'=>'200 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Cartographer&#39;s Tools','type'=>'Tool','cost'=>'15 gp','weight'=>'6 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Case, Crossbow Bolt','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'1 lb','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Case, Map or Scroll','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'1 lb','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Chain (10 feet)','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'10 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Chain Mail','type'=>'Heavy Armor','cost'=>'75 gp','weight'=>'55 lbs','description'=>'AC 16','notes'=>'Warding');
$stock[] = new array ('name'=>'Chain Shirt','type'=>'Medium Armor','cost'=>'50 gp','weight'=>'20 lbs','description'=>'AC 13','notes'=>'Warding');
$stock[] = new array ('name'=>'Chariot','type'=>'Vehicle (Land)','cost'=>'250 gp','weight'=>'100 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Chest','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'25 lbs','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Climber&#39;s Kit','type'=>'Adventuring Gear','cost'=>'25 gp','weight'=>'12 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Clothes, Costume','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'4 lbs','description'=>'','notes'=>'Deception, Outerwear, Social');
$stock[] = new array ('name'=>'Clothes, Fine','type'=>'Adventuring Gear','cost'=>'15 gp','weight'=>'6 lbs','description'=>'','notes'=>'Outerwear, Social');
$stock[] = new array ('name'=>'Clothes, Traveler&#39;s','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'4 lbs','description'=>'','notes'=>'Outerwear, Social');
$stock[] = new array ('name'=>'Cobbler&#39;s Tools','type'=>'Tool','cost'=>'5 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Component Pouch','type'=>'Adventuring Gear','cost'=>'25 gp','weight'=>'2 lbs','description'=>'','notes'=>'Container, Utility');
$stock[] = new array ('name'=>'Cook&#39;s Utensils','type'=>'Tool','cost'=>'1 gp','weight'=>'8 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Crawler Mucus (Contact)','type'=>'Poison','cost'=>'200 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Crossbow Bolts','type'=>'Ammunition','cost'=>'1 gp','weight'=>'1 1/2 lb','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Crossbow, Hand','type'=>'Martial Ranged Weapon','cost'=>'75 gp','weight'=>'3 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Crossbow, Heavy','type'=>'Martial Ranged Weapon','cost'=>'50 gp','weight'=>'18 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Crossbow, Light','type'=>'Simple Ranged Weapon','cost'=>'25 gp','weight'=>'5 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Crowbar','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'5 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Crystal','type'=>'Arcane Focus','cost'=>'10 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Dagger','type'=>'Simple Melee Weapon','cost'=>'2 gp','weight'=>'1 lb','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Diplomat&#39;s Pack','type'=>'Equipment Pack','cost'=>'39 gp','weight'=>'36 lbs','description'=>'','notes'=>'Container, Exploration, Outerwear, Social, Utility');
$stock[] = new array ('name'=>'Disguise Kit','type'=>'Tool','cost'=>'25 gp','weight'=>'3 lbs','description'=>'','notes'=>'Deception, Utility');
$stock[] = new array ('name'=>'Donkey (or Mule)','type'=>'Mount','cost'=>'8 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 420 lbs.');
$stock[] = new array ('name'=>'Double-Bladed Scimitar','type'=>'Martial Melee Weapon','cost'=>'100 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Draft Horse','type'=>'Mount','cost'=>'50 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 540 lbs.');
$stock[] = new array ('name'=>'Dragonchess Set','type'=>'Tool','cost'=>'1 gp','weight'=>'1/2 lb','description'=>'','notes'=>'Social');
$stock[] = new array ('name'=>'Drow Poison (Injury)','type'=>'Poison','cost'=>'200 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Drum','type'=>'Tool','cost'=>'6 gp','weight'=>'3 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Dulcimer','type'=>'Tool','cost'=>'25 gp','weight'=>'10 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Dungeoneer&#39;s Pack','type'=>'Equipment Pack','cost'=>'12 gp','weight'=>'61 1/2 lbs','description'=>'','notes'=>'Container, Exploration, Utility');
$stock[] = new array ('name'=>'Elephant','type'=>'Mount','cost'=>'200 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 1,320 lbs.');
$stock[] = new array ('name'=>'Emblem','type'=>'Holy Symbol','cost'=>'5 gp','weight'=>'--','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Entertainer&#39;s Pack','type'=>'Equipment Pack','cost'=>'40 gp','weight'=>'38 lbs','description'=>'','notes'=>'Container, Deception, Exploration, Outerwear, Social, Utility');
$stock[] = new array ('name'=>'Essence of Ether (Inhaled)','type'=>'Poison','cost'=>'300 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Explorer&#39;s Pack','type'=>'Equipment Pack','cost'=>'10 gp','weight'=>'59 lbs','description'=>'','notes'=>'Container, Exploration, Utility');
$stock[] = new array ('name'=>'Fishing Tackle','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'4 lbs','description'=>'','notes'=>'Social, Utility');
$stock[] = new array ('name'=>'Flail','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'2 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Flute','type'=>'Tool','cost'=>'2 gp','weight'=>'1 lb','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Forgery Kit','type'=>'Tool','cost'=>'15 gp','weight'=>'5 lbs','description'=>'','notes'=>'Deception, Utility');
$stock[] = new array ('name'=>'Galley','type'=>'Vehicle (Water)','cost'=>'30000 gp','weight'=>'--','description'=>'','notes'=>'Speed 4 mph');
$stock[] = new array ('name'=>'Glaive','type'=>'Martial Melee Weapon','cost'=>'20 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Control, Damage');
$stock[] = new array ('name'=>'Glassblower&#39;s Tools','type'=>'Tool','cost'=>'30 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Grappling Hook','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'4 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Greataxe','type'=>'Martial Melee Weapon','cost'=>'30 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Greatsword','type'=>'Martial Melee Weapon','cost'=>'50 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Gunpowder, Keg','type'=>'Adventuring Gear','cost'=>'250 gp','weight'=>'20 lbs','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Gunpowder, Powder Horn','type'=>'Adventuring Gear','cost'=>'35 gp','weight'=>'2 lbs','description'=>'','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Halberd','type'=>'Martial Melee Weapon','cost'=>'20 gp','weight'=>'6 lbs','description'=>'Slashing','notes'=>'Combat, Control, Damage');
$stock[] = new array ('name'=>'Half Plate','type'=>'Medium Armor','cost'=>'750 gp','weight'=>'40 lbs','description'=>'AC 15','notes'=>'Warding');
$stock[] = new array ('name'=>'Hammer','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'3 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Hammer, Sledge','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'10 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Handaxe','type'=>'Simple Melee Weapon','cost'=>'5 gp','weight'=>'2 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Healer&#39;s Kit','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'3 lbs','description'=>'','notes'=>'Combat, Healing');
$stock[] = new array ('name'=>'Herbalism Kit','type'=>'Tool','cost'=>'5 gp','weight'=>'3 lbs','description'=>'','notes'=>'Healing, Utility');
$stock[] = new array ('name'=>'Hide','type'=>'Medium Armor','cost'=>'10 gp','weight'=>'12 lbs','description'=>'AC 12','notes'=>'Warding');
$stock[] = new array ('name'=>'Holy Water (flask)','type'=>'Adventuring Gear','cost'=>'25 gp','weight'=>'1 lb','description'=>'','notes'=>'Combat, Damage, Utility');
$stock[] = new array ('name'=>'Horn','type'=>'Tool','cost'=>'3 gp','weight'=>'2 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Hourglass','type'=>'Adventuring Gear','cost'=>'25 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Hunting Trap','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'25 lbs','description'=>'','notes'=>'Damage, Utility');
$stock[] = new array ('name'=>'Ink (1 ounce bottle)','type'=>'Adventuring Gear','cost'=>'10 gp','weight'=>'--','description'=>'','notes'=>'Communication, Consumable, Social, Utility');
$stock[] = new array ('name'=>'Insect Repellant-Salve','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'--','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Jeweler&#39;s Tools','type'=>'Tool','cost'=>'25 gp','weight'=>'2 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Keelboat','type'=>'Vehicle (Water)','cost'=>'3000 gp','weight'=>'--','description'=>'','notes'=>'Speed 1 mph');
$stock[] = new array ('name'=>'Lance','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'6 lbs','description'=>'Piercing','notes'=>'Combat, Control, Damage');
$stock[] = new array ('name'=>'Lantern, Bullseye','type'=>'Adventuring Gear','cost'=>'10 gp','weight'=>'2 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Lantern, Hooded','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'2 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Leather','type'=>'Light Armor','cost'=>'10 gp','weight'=>'10 lbs','description'=>'AC 11','notes'=>'Warding');
$stock[] = new array ('name'=>'Leatherworker&#39;s Tools','type'=>'Tool','cost'=>'5 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Light Hammer','type'=>'Simple Melee Weapon','cost'=>'2 gp','weight'=>'2 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Lock','type'=>'Adventuring Gear','cost'=>'10 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility, Warding');
$stock[] = new array ('name'=>'Longbow','type'=>'Martial Ranged Weapon','cost'=>'50 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Longship','type'=>'Vehicle (Water)','cost'=>'10000 gp','weight'=>'--','description'=>'','notes'=>'Speed 3 mph');
$stock[] = new array ('name'=>'Longsword','type'=>'Martial Melee Weapon','cost'=>'15 gp','weight'=>'3 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Lute','type'=>'Tool','cost'=>'35 gp','weight'=>'2 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Lyre','type'=>'Tool','cost'=>'30 gp','weight'=>'2 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Mace','type'=>'Simple Melee Weapon','cost'=>'5 gp','weight'=>'4 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Magnifying Glass','type'=>'Adventuring Gear','cost'=>'100 gp','weight'=>'--','description'=>'','notes'=>'Detection, Exploration, Utility');
$stock[] = new array ('name'=>'Malice (Inhaled)','type'=>'Poison','cost'=>'250 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Manacles','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'6 lbs','description'=>'','notes'=>'Control, Utility');
$stock[] = new array ('name'=>'Mason&#39;s Tools','type'=>'Tool','cost'=>'10 gp','weight'=>'8 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Mastiff','type'=>'Mount','cost'=>'25 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 195 lbs.');
$stock[] = new array ('name'=>'Maul','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'10 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Midnight Tears (Ingested)','type'=>'Poison','cost'=>'1500 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage');
$stock[] = new array ('name'=>'Mirror, Steel','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'1/2 lb','description'=>'','notes'=>'Social, Utility');
$stock[] = new array ('name'=>'Monster Hunter&#39;s Pack','type'=>'Equipment Pack','cost'=>'33 gp','weight'=>'49 lbs','description'=>'','notes'=>'Container, Control, Utility');
$stock[] = new array ('name'=>'Morningstar','type'=>'Martial Melee Weapon','cost'=>'15 gp','weight'=>'4 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Musket','type'=>'Firearms Ranged Weapon','cost'=>'500 gp','weight'=>'10 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Navigator&#39;s Tools','type'=>'Tool','cost'=>'25 gp','weight'=>'2 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Net','type'=>'Martial Ranged Weapon','cost'=>'1 gp','weight'=>'3 lbs','description'=>'Bludgeoning','notes'=>'Combat, Control');
$stock[] = new array ('name'=>'Oil of Taggit (Contact)','type'=>'Poison','cost'=>'400 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Orb','type'=>'Arcane Focus','cost'=>'20 gp','weight'=>'3 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Padded','type'=>'Light Armor','cost'=>'5 gp','weight'=>'8 lbs','description'=>'AC 11','notes'=>'Warding');
$stock[] = new array ('name'=>'Painter&#39;s Supplies','type'=>'Tool','cost'=>'10 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Pale Tincture (Ingested)','type'=>'Poison','cost'=>'250 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Pan Flute','type'=>'Tool','cost'=>'12 gp','weight'=>'2 lbs','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Perfume (vial)','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Social, Utility');
$stock[] = new array ('name'=>'Pick, Miner&#39;s','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'10 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Pike','type'=>'Martial Melee Weapon','cost'=>'5 gp','weight'=>'18 lbs','description'=>'Piercing','notes'=>'Combat, Control, Damage');
$stock[] = new array ('name'=>'Pistol','type'=>'Firearms Ranged Weapon','cost'=>'250 gp','weight'=>'3 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Plate','type'=>'Heavy Armor','cost'=>'1500 gp','weight'=>'65 lbs','description'=>'AC 18','notes'=>'Warding');
$stock[] = new array ('name'=>'Poison, Basic (vial)','type'=>'Poison','cost'=>'100 gp','weight'=>'--','description'=>'','notes'=>'Combat, Consumable, Damage, Utility');
$stock[] = new array ('name'=>'Poisoner&#39;s Kit','type'=>'Tool','cost'=>'50 gp','weight'=>'2 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Pony','type'=>'Mount','cost'=>'30 gp','weight'=>'--','description'=>'','notes'=>'Speed 40 ft., Carrying Capacity 225 lbs.');
$stock[] = new array ('name'=>'Pot, Iron','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'10 lbs','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Potion of Healing','type'=>'Potion','cost'=>'50 gp','weight'=>'1/2 lb','description'=>'','notes'=>'Combat, Consumable, Healing');
$stock[] = new array ('name'=>'Potter&#39;s Tools','type'=>'Tool','cost'=>'10 gp','weight'=>'3 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Priest&#39;s Pack','type'=>'Equipment Pack','cost'=>'19 gp','weight'=>'24 lbs','description'=>'','notes'=>'Container, Exploration, Outerwear, Social, Utility');
$stock[] = new array ('name'=>'Purple Worm Poison (Injury)','type'=>'Poison','cost'=>'2000 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Quiver','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'1 lb','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Rain Catcher','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Ram, Portable','type'=>'Adventuring Gear','cost'=>'4 gp','weight'=>'35 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Rapier','type'=>'Martial Melee Weapon','cost'=>'25 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Reliquary','type'=>'Holy Symbol','cost'=>'5 gp','weight'=>'2 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Riding Horse','type'=>'Mount','cost'=>'75 gp','weight'=>'--','description'=>'','notes'=>'Speed 60 ft., Carrying Capacity 480 lbs.');
$stock[] = new array ('name'=>'Ring Mail','type'=>'Heavy Armor','cost'=>'30 gp','weight'=>'40 lbs','description'=>'AC 14','notes'=>'Warding');
$stock[] = new array ('name'=>'Robes','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'4 lbs','description'=>'','notes'=>'Outerwear, Utility');
$stock[] = new array ('name'=>'Rod','type'=>'Arcane Focus','cost'=>'10 gp','weight'=>'2 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Rope, Hempen (50 feet)','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'10 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Rope, Silk (50 feet)','type'=>'Adventuring Gear','cost'=>'10 gp','weight'=>'5 lbs','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Rowboat','type'=>'Vehicle (Water)','cost'=>'50 gp','weight'=>'100 lbs','description'=>'','notes'=>'Speed 1 1/2 mph');
$stock[] = new array ('name'=>'Saddle, Exotic','type'=>'Adventuring Gear','cost'=>'60 gp','weight'=>'40 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Saddle, Military','type'=>'Adventuring Gear','cost'=>'20 gp','weight'=>'30 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Saddle, Pack','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'15 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Saddle, Riding','type'=>'Adventuring Gear','cost'=>'10 gp','weight'=>'25 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Saddlebags','type'=>'Adventuring Gear','cost'=>'4 gp','weight'=>'8 lbs','description'=>'','notes'=>'Container, Utility');
$stock[] = new array ('name'=>'Sailing Ship','type'=>'Vehicle (Water)','cost'=>'10000 gp','weight'=>'--','description'=>'','notes'=>'Speed 2 mph');
$stock[] = new array ('name'=>'Scale Mail','type'=>'Medium Armor','cost'=>'50 gp','weight'=>'45 lbs','description'=>'AC 14','notes'=>'Warding');
$stock[] = new array ('name'=>'Scale, Merchant&#39;s','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'3 lbs','description'=>'','notes'=>'Social, Utility');
$stock[] = new array ('name'=>'Scholar&#39;s Pack','type'=>'Equipment Pack','cost'=>'40 gp','weight'=>'10 lbs','description'=>'','notes'=>'Container, Social, Utility');
$stock[] = new array ('name'=>'Scimitar','type'=>'Martial Melee Weapon','cost'=>'25 gp','weight'=>'3 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Serpent Venom (Injury)','type'=>'Poison','cost'=>'200 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Shawm','type'=>'Tool','cost'=>'2 gp','weight'=>'1 lb','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Shield','type'=>'Shield','cost'=>'10 gp','weight'=>'6 lbs','description'=>'AC 2','notes'=>'Warding');
$stock[] = new array ('name'=>'Shortbow','type'=>'Simple Ranged Weapon','cost'=>'25 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Shortsword','type'=>'Martial Melee Weapon','cost'=>'10 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Shovel','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Sickle','type'=>'Simple Melee Weapon','cost'=>'1 gp','weight'=>'2 lbs','description'=>'Slashing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Signet Ring','type'=>'Adventuring Gear','cost'=>'5 gp','weight'=>'--','description'=>'','notes'=>'Communication, Social, Utility');
$stock[] = new array ('name'=>'Sled','type'=>'Vehicle (Land)','cost'=>'20 gp','weight'=>'300 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Smith&#39;s Tools','type'=>'Tool','cost'=>'20 gp','weight'=>'8 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Spear','type'=>'Simple Melee Weapon','cost'=>'1 gp','weight'=>'3 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Spellbook','type'=>'Adventuring Gear','cost'=>'50 gp','weight'=>'3 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Spiked Armor','type'=>'Medium Armor','cost'=>'75 gp','weight'=>'45 lbs','description'=>'AC 14','notes'=>'Damage, Warding');
$stock[] = new array ('name'=>'Spikes, Iron (10)','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Splint','type'=>'Heavy Armor','cost'=>'200 gp','weight'=>'60 lbs','description'=>'AC 17','notes'=>'Warding');
$stock[] = new array ('name'=>'Sprig of Mistletoe','type'=>'Druidic Focus','cost'=>'1 gp','weight'=>'--','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Spyglass','type'=>'Adventuring Gear','cost'=>'1000 gp','weight'=>'1 lb','description'=>'','notes'=>'Exploration, Social, Utility');
$stock[] = new array ('name'=>'Staff','type'=>'Arcane Focus','cost'=>'5 gp','weight'=>'4 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Studded Leather','type'=>'Light Armor','cost'=>'45 gp','weight'=>'13 lbs','description'=>'AC 12','notes'=>'Warding');
$stock[] = new array ('name'=>'Tent, Two-Person','type'=>'Adventuring Gear','cost'=>'2 gp','weight'=>'20 lbs','description'=>'','notes'=>'Exploration, Social, Utility');
$stock[] = new array ('name'=>'Thieves&#39; Tools','type'=>'Tool','cost'=>'25 gp','weight'=>'1 lb','description'=>'','notes'=>'Exploration, Utility');
$stock[] = new array ('name'=>'Three-Dragon Ante Set','type'=>'Tool','cost'=>'1 gp','weight'=>'--','description'=>'','notes'=>'Social');
$stock[] = new array ('name'=>'Tinker&#39;s Tools','type'=>'Tool','cost'=>'50 gp','weight'=>'10 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Torpor (Ingested)','type'=>'Poison','cost'=>'600 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Totem','type'=>'Druidic Focus','cost'=>'1 gp','weight'=>'--','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Trident','type'=>'Martial Melee Weapon','cost'=>'5 gp','weight'=>'4 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Truth Serum (Ingested)','type'=>'Poison','cost'=>'150 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Debuff, Utility');
$stock[] = new array ('name'=>'Vial','type'=>'Adventuring Gear','cost'=>'1 gp','weight'=>'--','description'=>'','notes'=>'Container');
$stock[] = new array ('name'=>'Viol','type'=>'Tool','cost'=>'30 gp','weight'=>'1 lb','description'=>'','notes'=>'Instrument');
$stock[] = new array ('name'=>'Wagon','type'=>'Vehicle (Land)','cost'=>'35 gp','weight'=>'400 lbs','description'=>'','notes'=>'Exploration, Movement, Utility');
$stock[] = new array ('name'=>'Wand','type'=>'Arcane Focus','cost'=>'10 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'War Pick','type'=>'Martial Melee Weapon','cost'=>'5 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Warhammer','type'=>'Martial Melee Weapon','cost'=>'15 gp','weight'=>'2 lbs','description'=>'Bludgeoning','notes'=>'Combat, Damage');
$stock[] = new array ('name'=>'Warhorse','type'=>'Mount','cost'=>'400 gp','weight'=>'--','description'=>'','notes'=>'Speed 60 ft., Carry Capacity 540 lbs.');
$stock[] = new array ('name'=>'Warship','type'=>'Vehicle (Water)','cost'=>'25000 gp','weight'=>'--','description'=>'','notes'=>'2 1/2 mph');
$stock[] = new array ('name'=>'Weaver&#39;s Tools','type'=>'Tool','cost'=>'1 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Whip','type'=>'Martial Melee Weapon','cost'=>'2 gp','weight'=>'3 lbs','description'=>'Slashing','notes'=>'Combat, Control, Damage');
$stock[] = new array ('name'=>'Woodcarver&#39;s Tools','type'=>'Tool','cost'=>'1 gp','weight'=>'5 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Wooden Staff','type'=>'Druidic Focus','cost'=>'5 gp','weight'=>'4 lbs','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Wyvern Poison (Injury)','type'=>'Poison','cost'=>'1200 gp','weight'=>'--','description'=>'','notes'=>'Consumable, Damage, Debuff');
$stock[] = new array ('name'=>'Yew Wand','type'=>'Druidic Focus','cost'=>'10 gp','weight'=>'1 lb','description'=>'','notes'=>'Utility');
$stock[] = new array ('name'=>'Yklwa','type'=>'Simple Melee Weapon','cost'=>'1 gp','weight'=>'2 lbs','description'=>'Piercing','notes'=>'Combat, Damage');
